spring.application.name=api

# Console H2
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.h2.console.settings.web-allow-others=true   # apenas para teste

# Console H2 corrigido
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.web.mvc.pathmatch.use-suffix-pattern=true
# para leitura de .json



# BD H2 em memória
spring.datasource.url=jdbc:h2:mem:maisaude
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto H2 e DDL automático (cria as tabelas a partir das entities)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Exibir SQL no console (bom para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

